#define BAD_SYNTAX	1
#define TOO_SHAPE	2
#define IN_PRIMNAME	3
#define TOO_ATTR	4
#define TOO_OBJECT	5
#define TOO_LIGHT	6
#define MULT_CAM	7
#define NOT_CONST	8
#define BAD_CONST	9
#define EOF_IN_COMMENT	10
#define BAD_CHR		11
#define INVALOP		12
#define	MULT_CPOS	13
#define	MULT_CDIR	14
#define	MULT_CROT	15
#define	MULT_CZOOM	16
#define	MULT_CIRIS	17
#define	NO_CAMPOS	18
#define	MULT_SKY	19
#define	BAD_AXIS	20
#define	INV_OMIT	21
#define CANT_INPUT	22
#define	CANT_CREATE	23
#define	STR_TOOLONG	24
#define	FNAM_TOOLONG	25
#define	UNTERM_STRING	26

extern void int_error();
extern void error();
